/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.fallout_wastelands;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class FalloutWastelandsModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public FalloutWastelandsModElements() {
		sounds.put(new ResourceLocation("fallout_wastelands", "machinegun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "machinegun")));
		sounds.put(new ResourceLocation("fallout_wastelands", "gun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "gun")));
		sounds.put(new ResourceLocation("fallout_wastelands", "bulletground"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "bulletground")));
		sounds.put(new ResourceLocation("fallout_wastelands", "shotwound"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "shotwound")));
		sounds.put(new ResourceLocation("fallout_wastelands", "lasgun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "lasgun")));
		sounds.put(new ResourceLocation("fallout_wastelands", "spf"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "spf")));
		sounds.put(new ResourceLocation("fallout_wastelands", "uzi"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "uzi")));
		sounds.put(new ResourceLocation("fallout_wastelands", "ak47"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "ak47")));
		sounds.put(new ResourceLocation("fallout_wastelands", "ghoulliving"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "ghoulliving")));
		sounds.put(new ResourceLocation("fallout_wastelands", "ghoulinjured"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "ghoulinjured")));
		sounds.put(new ResourceLocation("fallout_wastelands", "ghouldeath"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "ghouldeath")));
		sounds.put(new ResourceLocation("fallout_wastelands", "playerdeath"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "playerdeath")));
		sounds.put(new ResourceLocation("fallout_wastelands", "robobraintracks"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "robobraintracks")));
		sounds.put(new ResourceLocation("fallout_wastelands", "robobrainliving"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "robobrainliving")));
		sounds.put(new ResourceLocation("fallout_wastelands", "robobrainshoot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "robobrainshoot")));
		sounds.put(new ResourceLocation("fallout_wastelands", "rbshoot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "rbshoot")));
		sounds.put(new ResourceLocation("fallout_wastelands", "rblfix"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "rblfix")));
		sounds.put(new ResourceLocation("fallout_wastelands", "rbwfix"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "rbwfix")));
		sounds.put(new ResourceLocation("fallout_wastelands", "robotfireing"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "robotfireing")));
		sounds.put(new ResourceLocation("fallout_wastelands", "lasershoot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "lasershoot")));
		sounds.put(new ResourceLocation("fallout_wastelands", "supermutantliving"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "supermutantliving")));
		sounds.put(new ResourceLocation("fallout_wastelands", "bloatflydeath"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "bloatflydeath")));
		sounds.put(new ResourceLocation("fallout_wastelands", "bloatflyidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "bloatflyidle")));
		sounds.put(new ResourceLocation("fallout_wastelands", "bloatflyinjured"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "bloatflyinjured")));
		sounds.put(new ResourceLocation("fallout_wastelands", "bloatflyattack"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "bloatflyattack")));
		sounds.put(new ResourceLocation("fallout_wastelands", "supermutant"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "supermutant")));
		sounds.put(new ResourceLocation("fallout_wastelands", "nailgunshooting"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "nailgunshooting")));
		sounds.put(new ResourceLocation("fallout_wastelands", "reaper"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "reaper")));
		sounds.put(new ResourceLocation("fallout_wastelands", "highwaymanmounting"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "highwaymanmounting")));
		sounds.put(new ResourceLocation("fallout_wastelands", "highwaymanstep"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "highwaymanstep")));
		sounds.put(new ResourceLocation("fallout_wastelands", "menutheme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "menutheme")));
		sounds.put(new ResourceLocation("fallout_wastelands", "tenmm"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "tenmm")));
		sounds.put(new ResourceLocation("fallout_wastelands", "tenmmshot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "tenmmshot")));
		sounds.put(new ResourceLocation("fallout_wastelands", "plasmarifle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "plasmarifle")));
		sounds.put(new ResourceLocation("fallout_wastelands", "wastelandwind"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "wastelandwind")));
		sounds.put(new ResourceLocation("fallout_wastelands", "ninemmshot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "ninemmshot")));
		sounds.put(new ResourceLocation("fallout_wastelands", "ninemmshotb"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "ninemmshotb")));
		sounds.put(new ResourceLocation("fallout_wastelands", "tenmmshootb"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "tenmmshootb")));
		sounds.put(new ResourceLocation("fallout_wastelands", "rbshot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "rbshot")));
		sounds.put(new ResourceLocation("fallout_wastelands", "tenmmc"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "tenmmc")));
		sounds.put(new ResourceLocation("fallout_wastelands", "portalentrance"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "portalentrance")));
		sounds.put(new ResourceLocation("fallout_wastelands", "radiation"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "radiation")));
		sounds.put(new ResourceLocation("fallout_wastelands", "machinegunreload"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "machinegunreload")));
		sounds.put(new ResourceLocation("fallout_wastelands", "laserriflereload"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "laserriflereload")));
		sounds.put(new ResourceLocation("fallout_wastelands", "emptygunfire"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "emptygunfire")));
		sounds.put(new ResourceLocation("fallout_wastelands", "removingfusioncell"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "removingfusioncell")));
		sounds.put(new ResourceLocation("fallout_wastelands", "pistol10mmreload"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "pistol10mmreload")));
		sounds.put(new ResourceLocation("fallout_wastelands", "pistol9mmreload"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "pistol9mmreload")));
		sounds.put(new ResourceLocation("fallout_wastelands", "bigfallboom"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "bigfallboom")));
		sounds.put(new ResourceLocation("fallout_wastelands", "armorhitbyarrow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "armorhitbyarrow")));
		sounds.put(new ResourceLocation("fallout_wastelands", "smallfallboom"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallout_wastelands", "smallfallboom")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("fallout_wastelands").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == FalloutWastelandsModElements.ModElement.class)
						elements.add((FalloutWastelandsModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(FalloutWastelandsModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new FalloutWastelandsModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		FalloutWastelandsMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final FalloutWastelandsModElements elements;
		protected final int sortid;

		public ModElement(FalloutWastelandsModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
